'\" t
.\"     Title: xdg-user-dirs-update
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 02/15/2019
.\"    Manual: User Commands
.\"    Source: XDG
.\"  Language: English
.\"
.TH "XDG\-USER\-DIRS\-UPD" "1" "" "XDG" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xdg-user-dirs-update \- Update XDG user dir configuration
.SH "SYNOPSIS"
.HP \w'\fBxdg\-user\-dirs\-update\fR\ 'u
\fBxdg\-user\-dirs\-update\fR [OPTION...] [\-\-set\ \fINAME\fR\ \fIPATH\fR...]
.SH "DESCRIPTION"
.PP
\fBxdg\-user\-dirs\-update\fR
updates the current state of the users
user\-dirs\&.dir\&. If none existed before then one is created based on the system default values, or falling back to the old non\-translated filenames if such directories exists\&. The list of old directories used are:
~/Desktop,
~/Templates
and
~/Public\&.
.PP
If an old configuration exists it is updated with any new default directories\&. Additionally, any configured directories that point to non\-existing locations are reset by pointing then to the users home directory\&. This typically happens when the users removed the directory, so they likely don\*(Aqt want to use it anymore\&.
.PP
On the first run a
user\-dirs\&.locale
file is created containing the locale that was used for the translation\&. This is used later by GUI tools like
\fBxdg\-user\-dirs\-gtk\-update\fR
to detect if the locale was changed, letting you to migrate from the old names\&.
.PP
\fBxdg\-user\-dirs\-update\fR
is normally run automatically at the start of a user session to update the XDG user dirs according to the users locale\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-help\fR
.RS 4
Print help output and exit\&.
.RE
.PP
\fB\-\-force\fR
.RS 4
Update existing
user\-dirs\&.dir, but force a full reset\&. This means: Don\*(Aqt reset nonexisting directories to HOME, rather recreate the directory\&. Never use backwards compatible non\-translated names\&. Always recreate
user\-dirs\&.locale\&.
.RE
.PP
\fB\-\-dummy\-output \fR\fB\fIPATH\fR\fR
.RS 4
Write the configuration to
\fIPATH\fR
instead of the default configuration file\&. Also, no directories are created\&.
.RE
.PP
\fB\-\-set \fR\fB\fINAME\fR\fR\fB \fR\fB\fIPATH\fR\fR
.RS 4
Sets the XDG user dir with the given name\&.
.sp
\fINAME\fR
should be one of the following:
.RS 4
DESKTOP
.RE
.RS 4
DOWNLOAD
.RE
.RS 4
TEMPLATES
.RE
.RS 4
PUBLICSHARE
.RE
.RS 4
DOCUMENTS
.RE
.RS 4
MUSIC
.RE
.RS 4
PICTURES
.RE
.RS 4
VIDEOS
.RE
.sp
\fIPATH\fR
must be an absolute path, e\&.g\&.
$HOME/Some/Directory\&.
.RE
.SH "FILES"
.PP
The XDG user dirs configuration is stored in the
user\-dirs\&.dir
file in the location pointed to by the
\fBXDG_CONFIG_HOME\fR
environment variable\&.
.SH "ENVIRONMENT"
.PP
The
\fBXDG_CONFIG_HOME\fR
environment variable determines where the
user\-dirs\&.dirs
file is located\&.
.SH "SEE ALSO"
.PP
\fBxdg-user-dir\fR(1),
\fBuser-dirs.dirs\fR(5),
\fBuser-dirs.defaults\fR(5),
\fBuser-dirs.conf\fR(5)\&.
